model:
  type: Bert
dataset:
  path: ./taa/data
  name: imdb
  data_dir:
  data_files: {'train': 'custom_data_train.csv', 'test': 'custom_data_test.csv'}
  text_key: text
abspath: ./model_english_data
aug: imdb
per_device_train_batch_size: 64
per_device_eval_batch_size: 128
epoch: 10
lr: 4e-5
max_seq_length: 128
n_aug: 4
num_op: 2
num_policy: 4
method: taa
topN: 3
ir: 1
seed: 59
trail: 1
train:
  npc: 20
valid:
  npc: 20
test:
  npc: 20  
num_search: 200
num_gpus: 1
num_cpus: 8
